inaka/shotgun

Makefile
erlang.mk

* remove -s sync from RUN command and in shell target.

Remove Sync as dependency

---

Makefile
rebar.config
src/shotgun.app.src

[Closes #76] Remove lager dep

---

Makefile

[Closes #73] Update gun version

---

rebar.config

[#73] Update gun version, in rebar.config as well

---

CHANGELOG.md
Makefile
src/shotgun.app.src

[Fix #80] Gun dependencies updated to 1.0.0-pre.1

---

CHANGELOG.md

[Fix #80] Version Bump 0.1.9

---

rebar.config

[fix #83] Update Gun dependency to 1.0.0-pre.1

---

CHANGELOG.md
src/shotgun.app.src

Fix #85 Version bump to 0.1.10

[Fix #85] Version bump to 0.1.10

---

.gitignore
src/shotgun.erl

[#88] fix unrecognised events in parse_event()

---

.gitignore

Error reply

---

.gitignore
erlang.mk
src/shotgun.erl
src/shotgun_app.erl
src/shotgun_sup.erl

- Replace all refs to asyn_data to async_mode.
- Project dialyzed.

[Closes #107][Closes #106] Fix parse event spec

---

src/shotgun.erl

[#110] Return data as a binary

---

src/shotgun.erl
src/shotgun_sup.erl

Dialyzer fixes and firx for encode basic auth

---

src/shotgun.erl

(#45) Add last_event_id per sse spec

---

src/shotgun.erl

Reverts inaka/shotgun#128, merged by accident

Revert "(#45) Add last_event_id per sse spec"

---

.gitignore
Makefile
erlang.mk
src/shotgun.erl
test/cover.spec
test/http_server.app
test/http_server/http_base_handler.erl
test/http_server/http_basic_auth_handler.erl
test/http_server/http_binary_handler.erl
test/http_server/http_server.erl
test/http_server/http_server_sup.erl
test/http_server/http_simple_handler.erl
test/http_server/http_sse_handler.erl
test/shotgun_SUITE.erl
test/shotgun_async_SUITE.erl
test/shotgun_meta_SUITE.erl
test/shotgun_test_utils.erl

[Closes #98] Added tests and improved code

---

CHANGELOG.md
Makefile
src/shotgun.app.src

Version Bump to 0.2.1

---

Makefile

[Fix #114] update cowboy and cowlib version

[Fix #114] update cowboy and cowlib version

---

CHANGELOG.md
src/shotgun.app.src

[Close #146] version bump

---

src/shotgun.erl

(Yes, fully tested this time @elbrujohalcon)

Fixes a dialyzer warning and an error on the types sent to start_link

---

src/shotgun.erl

New option gun_opts provides base options for gun, this is continuation of #171

Allow to pass options to gun 
